import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import WorkoutProvider from "@/contexts/WorkoutContext";

const oswald = Oswald({
	variable: "--font-oswald",
	subsets: ["latin"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en" className={`${oswald.variable} ${inter.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col bg-background text-white font-secondary">
				<WorkoutProvider>
					<Navbar />
					<main>{children}</main>
					<Footer />
				</WorkoutProvider>
			</body>
		</html>
	);
}
